In [8]:
import numpy as np
a=np.zeros(3)
type(a[0])

numpy.float64

In [10]:
z=np.zeros(10)
z

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [12]:
z.shape
z.shape=(10,1)
z

array([[0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.],
       [0.]])

In [13]:
z=np.ones(3)
z

array([1., 1., 1.])

In [14]:
z=np.empty(3)
z

array([1., 1., 1.])

In [16]:
z=np.linspace(2,10,5)
z

array([ 2.,  4.,  6.,  8., 10.])

In [19]:
z=np.array([10,20])
z

array([10, 20])

In [20]:
a_list=[1,2,3,4,5,6,7]
z=np.array([a_list])
z

array([[1, 2, 3, 4, 5, 6, 7]])

In [25]:
#2D ARRAY
b_list=([9,8,7,6,5,4,3],[1,2,3,4,5,6,7])
z=np.array([b_list])
z.shape

(1, 2, 7)

In [29]:
np.random.seed(0)
z1=np.random.randint(10,size=6)
z1[0]
z1[0:3]
z1[-1]

np.int32(9)

In [33]:
import numpy as np
z=np.ones(10)
z

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [34]:
a_list=([1,2,3,4,5,6,7],[9,8,7,6,5,4,3])
z=np.array([a_list])
z

array([[[1, 2, 3, 4, 5, 6, 7],
        [9, 8, 7, 6, 5, 4, 3]]])

In [46]:
myarr=np.array([[3,6,32,7]],np.int8)
myarr[0,1]
myarr.shape
myarr.dtype
myarr[0,1]=45
myarr

array([[ 3, 45, 32,  7]], dtype=int8)

In [57]:
listarray=np.array([[1,2,3],[5,8,5],[0,3,1]])
listarray
listarray[1:5]

array([[5, 8, 5],
       [0, 3, 1]])

1) Arange
listarray=np.arange(10) = from 0 to n-1
listarray
2) Ones
listarray=np.ones(4)
listarray
3) Zeros
listarray=np.zeros(4)
listarray
[listarray.shape]
[listarray.dtype]
[listarray.size]
4) lspace=np.linspace(1,5,12) = gives 1 to 5 equally linspace 12 elements
lspace
5) emp=np.empty((4,6)) = gives random element
emp

In [60]:
listarray=np.arange(10)
listarray

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
listarray=np.ones((2,5)) #(rows, columns)
listarray

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [62]:
listarray=np.zeros(4)
listarray

array([0., 0., 0., 0.])

In [63]:
listarray=np.zeros((2,5))
listarray

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

In [69]:
lspace=np.linspace(1,5,4)
lspace

array([1.        , 2.33333333, 3.66666667, 5.        ])

In [70]:
emp=np.empty((4,6))
emp

array([[4.67296746e-307, 1.69121096e-306, 3.11522054e-307,
        1.42413555e-306, 1.78019082e-306, 1.37960147e-306],
       [1.33511562e-306, 2.22518251e-306, 1.33511969e-306,
        1.78022342e-306, 1.05700345e-307, 1.69118108e-306],
       [8.06632139e-308, 1.20160711e-306, 1.69119330e-306,
        2.22518251e-306, 1.33511969e-306, 1.60220393e-306],
       [1.33511562e-306, 7.56602523e-307, 1.95820760e-306,
        9.34601642e-307, 1.42410974e-306, 8.91238233e-313]])